### ISSUE TITLE
update analyze docstrings

### ISSUE THREAD

**Issue by blakeboswell** [blakeboswell/valence#11]
In addition to the comprehensive GCQuant class, the following functions are now exposed to the end user:
- `match_area`  (`compiled` is a protected word)
- `std_curves`
- `concentrations`
- `concentrations_exp`
- `concentrations_std`

I went through and added doc string templates to a few.  Need to fill in content and make any function name changes that are appropriate.

Additionally add comments to the docstrings for `GCQuant`.

**Comment by wilsoa6** [comment]
Doc strings updated. Take a look and see if everything looks ok. Change as needed and merge.
