### ISSUE TITLE
std_curve zero variance

### ISSUE THREAD

**Issue by blakeboswell** [blakeboswell/valence#12]
We can't do this: `warnings.filterwarnings("ignore")` because it will prevent the user from seeing warnings from `scipy` when doing things not associated with the `std_curve` calculation.

The warnings that we see after removing the above are the result of `cal_conc` in `matched_cal_conc` having 0 variance.  Is this right?  There's no need to regress if `x=1` and `intercept=0`.

**Comment by wilsoa6** [comment]
i believe this is occurring when there is only one datapoint for the specific chemical, i wasnt sure the easiest way to mute the error using the linreg

**Comment by blakeboswell** [comment]
When using `data/test3`, and looking at the `matched_calc_conc` data frame i was seeing the observations within each group all having the same `calc_conc`.  its possible i didn't know what i was looking at though.
