### ISSUE TITLE
update valence-on-rails repository

### ISSUE THREAD

**Issue by blakeboswell** [blakeboswell/valence#18]
The `valence-on-rails` repository will serve as a short-term documentation on how to use `valence` in practice as `jupyter notebooks`.

This task is specifically about preparing this repository for v0.0.1 release.

- `valence.build`
- `valence.analyze`
-  repository readme

Longer term we will create one documentation site with `on-rails` documentation and low-level api documentation .. but thats another issue.

**Comment by wilsoa6** [comment]
Update completed
